# Generated by Django 5.0.6 on 2024-06-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bracelets', to='shop.group'),
        ),
        migrations.AddField(
            model_name='charm',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='shop.group'),
        ),
        migrations.AddField(
            model_name='earring',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='earrings', to='shop.group'),
        ),
        migrations.AddField(
            model_name='pendant',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pendants', to='shop.group'),
        ),
        migrations.AddField(
            model_name='ring',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rings', to='shop.group'),
        ),
        migrations.AddField(
            model_name='watch',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='shop.group'),
        ),
    ]
