# Generated by Django 5.0.6 on 2024-06-17 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bracelet_group_charm_group_earring_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='jewelry_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='price',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='price',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='description',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='id',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='image',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='name',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pendant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='price',
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelets', to='shop.group'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charms', to='shop.group'),
        ),
        migrations.AlterField(
            model_name='earring',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earrings', to='shop.group'),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendants', to='shop.group'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rings', to='shop.group'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches', to='shop.group'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.jewelry')),
            ],
        ),
        migrations.AddField(
            model_name='bracelet',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charm',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earring',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendant',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ring',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='jewelry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.jewelry'),
            preserve_default=False,
        ),
    ]
