# Generated by Django 5.0.6 on 2024-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_jewelry_remove_bracelet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracelet',
            options={'verbose_name': 'Bracelet', 'verbose_name_plural': 'Bracelets'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
        migrations.AlterModelOptions(
            name='charm',
            options={'verbose_name': 'Charm', 'verbose_name_plural': 'Charms'},
        ),
        migrations.AlterModelOptions(
            name='earring',
            options={'verbose_name': 'Earring', 'verbose_name_plural': 'Earrings'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name': 'Jewelry', 'verbose_name_plural': 'Jewelry'},
        ),
        migrations.AlterModelOptions(
            name='pendant',
            options={'verbose_name': 'Pendant', 'verbose_name_plural': 'Pendants'},
        ),
        migrations.AlterModelOptions(
            name='ring',
            options={'verbose_name': 'Ring', 'verbose_name_plural': 'Rings'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Watches'},
        ),
    ]
